namespace day_2022_12_14.tests;

public class FiniteCaveTests
{
    private const string Data = @"
498,4 -> 498,6 -> 496,6
503,4 -> 502,4 -> 502,9 -> 494,9";

    private const string Cave = @"
............+............
.........................
.........................
.........................
..........#...##.........
..........#...#..........
........###...#..........
..............#..........
..............#..........
......#########..........
.........................
#########################";
    
    [Test]
    public void CreationFromData_Works_Correctly()
    {
        Assert.That(Environment.NewLine + new FiniteCave(Parser.Parse(Data), 500, 0), Is.EqualTo(Cave));
    }

    private const string FilledCave = @"
............+............
...........ooo...........
..........ooooo..........
.........ooooooo.........
........oo#ooo##o........
.......ooo#ooo#ooo.......
......oo###ooo#oooo......
.....oooo.oooo#ooooo.....
....oooooooooo#oooooo....
...ooo#########ooooooo...
..ooooo.......ooooooooo..
#########################";
    
    [Test]
    public void FillWithSand_Works_Correctly()
    {
        var cave = new FiniteCave(Parser.Parse(Data), 500, 0);
        cave.FillWithSand();
        Assert.That(Environment.NewLine + cave, Is.EqualTo(FilledCave));
    }
}